const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const source = fs.readFileSync(require('node:path').join(__dirname, '../docs/vm-control/admin.js'), 'utf8');
const cut = (a,b) => source.slice(source.indexOf(a), source.indexOf(b, source.indexOf(a)+a.length));
const code = cut('  function runtimeComponentRow(', '  async function refreshRuntimeCatalogInBackground(') + cut('  async function updateRuntimeImages(', '  async function updateCompatibility(');
const makeCatalog = () => ({schemaVersion:2,updatedAt:'2026-09-08T12:00:00Z',lastCheckedAt:'2026-09-08T12:00:00Z',stale:false,source:'docker-hub',components:{'steam-headless':{label:'Steam',complete:true,totalTags:11,supportedTags:3,excludedTags:8,candidates:[{tag:'latest',aliases:['latest','debian'],imageRef:'ref1',updatedAt:'2026-09-05'},{tag:'debian-0.2.0',imageRef:'ref2'}]},minecraft:{candidates:[]}}});
const endpoints = ['vm1','vm2'].map(id=>({id,instanceName:id,instanceState:'RUNNING',runtimeImages:{'steam-headless':{currentRef:'ref1'}},runtimeImageCapabilities:{'steam-headless':{canPull:true,canApply:true,canRollback:true}}}));
const context = vm.createContext({state:{runtimeImagesPayload:{catalog:makeCatalog(),endpoints},runtimeCatalogSnapshot:null,runtimeTargetSelections:{},runtimeCatalogAutoAttemptAt:0,runtimeCatalogRefreshInFlight:false},elements:{runtimeEndpoint:{value:'vm1'},runtimeImagesList:{innerHTML:''},refreshRuntimeImages:{}},vmEndpoints:value=>value,escapeHtml:value=>String(value).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/"/g,'&quot;'),queueMicrotask:()=>{context.queued=(context.queued||0)+1;},refreshRuntimeCatalogInBackground:()=>{},setMessage:(text,tone)=>{context.message={text,tone};},fetchApi:async()=>context.reply});
vm.runInContext(code, context);
vm.runInContext('renderRuntimeImages()',context);
assert.match(context.elements.runtimeImagesList.innerHTML,/latest \/ debian/);
context.state.runtimeTargetSelections['vm1:steam-headless']='ref2';
vm.runInContext('renderRuntimeImages()',context);
assert.match(context.elements.runtimeImagesList.innerHTML,/value="ref2" selected/);
context.elements.runtimeEndpoint.value='vm2';
vm.runInContext('renderRuntimeImages()',context);
assert.match(context.elements.runtimeImagesList.innerHTML,/value="ref1" selected/);
context.elements.runtimeEndpoint.value='vm1';
vm.runInContext('renderRuntimeImages()',context);
assert.match(context.elements.runtimeImagesList.innerHTML,/value="ref2" selected/);
context.state.runtimeImagesPayload.catalog={...makeCatalog(),schemaVersion:0,updatedAt:'2026-07-27T00:00:00Z',lastCheckedAt:''};
vm.runInContext('renderRuntimeImages()',context);
assert.equal(context.state.runtimeImagesPayload.catalog.schemaVersion,2);
context.state.runtimeCatalogSnapshot=null;
context.state.runtimeImagesPayload.catalog={...makeCatalog(),stale:true};
vm.runInContext('renderRuntimeImages();renderRuntimeImages()',context);
assert.equal(context.queued,1);
context.state.runtimeImagesPayload.catalog=makeCatalog();
context.state.runtimeImagesPayload.catalog.components['steam-headless'].candidates=context.state.runtimeImagesPayload.catalog.components['steam-headless'].candidates.slice(0,1);
vm.runInContext('renderRuntimeImages()',context);
assert.match(context.elements.runtimeImagesList.innerHTML,/Previous target is no longer listed/);
context.reply={catalog:{...makeCatalog(),stale:true,lastError:'Upstream <offline>',lastAttemptAt:'2026-09-08T13:00:00Z',retryAfterSeconds:300},endpoints};
(async()=>{await vm.runInContext('updateRuntimeImages("refresh-catalog", "")',context);assert.equal(context.message.tone,'warning');assert.match(context.elements.runtimeImagesList.innerHTML,/Upstream &lt;offline>/);assert.doesNotMatch(context.message.text,/versions refreshed/);console.log('PASS: 8 runtime catalog UI checks');})().catch(error=>{console.error(error);process.exitCode=1;});
